main:
  build:
    - stages:
        - name: build
          script: echo "Building static site"
  deploy:
    - name: deploy
      script: echo "Deploying to GitHub Pages"
      artifact: project/
      website: true